Controllers/StaffController.cs
using FinalProject.Data;
using FinalProject.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Globalization;

namespace FinalProject.Controllers
{
    public class StaffController : Controller
    {
        private readonly ILogger<StaffController> _logger;
        private SystemDBContext _context;

        public StaffController(ILogger<StaffController> logger, SystemDBContext context)
        {
            _logger = logger;
            _context = context;
        }
        public IActionResult Index()
        {
            var allRooms = _context.Rooms.ToList();
            var topRoooms = _context.Rooms.Take(3).ToList();
            var topRestaurantMenusBreak = _context.RestaurantMenus.Where(b => b.Meal.Contains("Breakfast")).Take(3).ToList();
            var topRestaurantMenusLun = _context.RestaurantMenus.Where(b => b.Meal.Contains("Lunch")).Take(3).ToList();
            var topRestaurantMenusDin = _context.RestaurantMenus.Where(b => b.Meal.Contains("Dinner")).Take(3).ToList();
            var room = new IndexViews
            {
                AllRooms = allRooms,
                TopRooms = topRoooms,
                TopRestaurantMenusBreak = topRestaurantMenusBreak,
                TopRestaurantMenusLun = topRestaurantMenusLun,
                TopRestaurantMenusDin = topRestaurantMenusDin,
                DemandRooms = allRooms
            };
            return View("Index", room);
        }
        public IActionResult rooms()
        {
            var allRooms = _context.Rooms.ToList();
            var topRoooms = _context.Rooms.Take(3).ToList();
            var room = new RoomsViews
            {
                AllRooms = allRooms,
                TopRooms = topRoooms
            };
            return View("RoomStaff", room);
        }
        [HttpPost]
        public IActionResult CheckAvailability(string checkin_date, string checkout_date, int adults, int children)
        {
            var allRooms = _context.Rooms.ToList();
            var topRoooms = _context.Rooms.Take(3).ToList();
            DateTime resCheckInDate;
            DateTime resCheckOutDate;

            var topRestaurantMenusBreak = _context.RestaurantMenus.Where(b => b.Meal.Contains("Breakfast")).Take(3).ToList();
            var topRestaurantMenusLun = _context.RestaurantMenus.Where(b => b.Meal.Contains("Lunch")).Take(3).ToList();
            var topRestaurantMenusDin = _context.RestaurantMenus.Where(b => b.Meal.Contains("Dinner")).Take(3).ToList();

            if (DateTime.TryParseExact(checkin_date, "d MMMM, yyyy", CultureInfo.InvariantCulture, DateTimeStyles.None, out resCheckInDate) && DateTime.TryParse(checkout_date, out resCheckOutDate))
            {
                var demandRooms = _context.Rooms
                                      .Where(room => room.Adults >= adults && room.Children >= children)
                                      .Where(room => room.RoomBookings.All(booking =>
                                      (booking.CheckIn < resCheckInDate && booking.CheckOut < resCheckInDate) ||
                                      (booking.CheckIn > resCheckOutDate && booking.CheckOut > resCheckOutDate)))
                                      .ToList();
                var room = new IndexViews
                {
                    AllRooms = allRooms,
                    TopRooms = topRoooms,
                    TopRestaurantMenusBreak = topRestaurantMenusBreak,
                    TopRestaurantMenusLun = topRestaurantMenusLun,
                    TopRestaurantMenusDin = topRestaurantMenusDin,
                    DemandRooms = demandRooms
                };
                return View("Index", room);
            }
            else
            {
                var room = new IndexViews
                {
                    AllRooms = allRooms,
                    TopRooms = topRoooms,
                    TopRestaurantMenusBreak = topRestaurantMenusBreak,
                    TopRestaurantMenusLun = topRestaurantMenusLun,
                    TopRestaurantMenusDin = topRestaurantMenusDin,
                    DemandRooms = allRooms
                };
                return View("Index", room);
            }
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<!-- Mirrored from preview.colorlib.com/theme/brighthotel/ by HTTrack Website Copier/3.x [XR&CO'2014], Sun, 08 Oct 2023 16:10:38 GMT -->
<head>
    <title>Bright Hotel - Free Bootstrap 4 Template by Colorlib</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link href="https://fonts.googleapis.com/css?family=Rubik:300,400,500" rel="stylesheet">
    <link rel="stylesheet" href="~/css/open-iconic-bootstrap.min.css">
    <link rel="stylesheet" href="~/css/animate.css">
    <link rel="stylesheet" href="~/css/owl.carousel.min.css">
    <link rel="stylesheet" href="~/css/owl.theme.default.min.css">
    <link rel="stylesheet" href="~/css/magnific-popup.css">
    <link rel="stylesheet" href="~/css/aos.css">
    <link rel="stylesheet" href="~/css/ionicons.min.css">
    <link rel="stylesheet" href="~/css/bootstrap-datepicker.css">
    <link rel="stylesheet" href="~/css/jquery.timepicker.css">
    <link rel="stylesheet" href="~/css/flaticon.css">
    <link rel="stylesheet" href="~/css/icomoon.css">
    <link rel="stylesheet" href="~/css/style.css">
    <script nonce="4516a2da-1752-4584-bdf4-697bcb381c29">(function (w, d) { !function (a, b, c, d) { a[c] = a[c] || {}; a[c].executed = []; a.zaraz = { deferred: [], listeners: [] }; a.zaraz.q = []; a.zaraz._f = function (e) { return async function () { var f = Array.prototype.slice.call(arguments); a.zaraz.q.push({ m: e, a: f }) } }; for (const g of ["track", "set", "debug"]) a.zaraz[g] = a.zaraz._f(g); a.zaraz.init = () => { var h = b.getElementsByTagName(d)[0], i = b.createElement(d), j = b.getElementsByTagName("title")[0]; j && (a[c].t = b.getElementsByTagName("title")[0].text); a[c].x = Math.random(); a[c].w = a.screen.width; a[c].h = a.screen.height; a[c].j = a.innerHeight; a[c].e = a.innerWidth; a[c].l = a.location.href; a[c].r = b.referrer; a[c].k = a.screen.colorDepth; a[c].n = b.characterSet; a[c].o = (new Date).getTimezoneOffset(); if (a.dataLayer) for (const n of Object.entries(Object.entries(dataLayer).reduce(((o, p) => ({ ...o[1], ...p[1] })), {}))) zaraz.set(n[0], n[1], { scope: "page" }); a[c].q = []; for (; a.zaraz.q.length;) { const q = a.zaraz.q.shift(); a[c].q.push(q) } i.defer = !0; for (const r of [localStorage, sessionStorage]) Object.keys(r || {}).filter((t => t.startsWith("_zaraz_"))).forEach((s => { try { a[c]["z_" + s.slice(7)] = JSON.parse(r.getItem(s)) } catch { a[c]["z_" + s.slice(7)] = r.getItem(s) } })); i.referrerPolicy = "origin"; i.src = "../../cdn-cgi/zaraz/sd0d9.js?z=" + btoa(encodeURIComponent(JSON.stringify(a[c]))); h.parentNode.insertBefore(i, h) };["complete", "interactive"].includes(b.readyState) ? zaraz.init() : a.addEventListener("DOMContentLoaded", zaraz.init) }(w, d, "zarazData", "script"); })(window, document);</script>
</head>

<body>
              

    <header>
        <nav class="navbar navbar-expand-lg navbar-dark ftco_navbar bg-dark ftco-navbar-light" style="background: transparent !important;position: absolute; " id="ftco-navbar">
            <div class="container">
                <a class="navbar-brand">BrightHotel</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#ftco-nav" aria-controls="ftco-nav" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="oi oi-menu"></span> Menu
                </button>
                <div class="collapse navbar-collapse" id="ftco-nav">
                    <ul class="navbar-nav ml-auto">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="rooms">Rooms</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="services">Services</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="about">About Us</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="blog">BLog</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Login" asp-action="login">Đăng nhập</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>

    

    @RenderBody();
    @await RenderSectionAsync("Scripts", required: false)

    <footer class="footer">
        <div class="container">
            <div class="row mb-5">
                <div class="col-md-6 col-lg-4">
                    <h3 class="heading-section">About Us</h3>
                    <p class="mb-5">
                        Lorem ipsum dolor sit amet consectetur adipisicing elit. Fuga aliquid. Atque dolore esse
                        veritatis iusto eaque perferendis non dolorem fugiat voluptatibus vitae error ad itaque inventore
                        accusantium tempore dolores sunt.
                    </p>
                    <p><a class="btn btn-primary px-4">Button</a></p>
                </div>
                <div class="col-md-6 col-lg-4">
                    <h3 class="heading-section">Blog</h3>
                    <div class="block-21 d-flex mb-4">
                        <figure class="mr-3">
                            <img src="images/img_1.jpg" alt class="img-fluid"> 
                        </figure>
                        <div class="text">
                            <h3 class="heading"><a >Our Luxury Hotel &amp; Restaurants</a></h3>
                            <div class="meta">
                                <div><a ><span class="icon-calendar"></span> May 29, 2018</a></div>
                                <div><a ><span class="icon-person"></span> Admin</a></div>
                                <div><a ><span class="icon-chat"></span> 19</a></div>
                            </div>
                        </div>
                    </div>
                    <div class="block-21 d-flex mb-4">
                        <figure class="mr-3">
                            <img src="images/img_2.jpg" alt class="img-fluid">
                        </figure>
                        <div class="text">
                            <h3 class="heading"><a >Our Luxury Hotel &amp; Restaurants</a></h3>
                            <div class="meta">
                                <div><a><span class="icon-calendar"></span> May 29, 2018</a></div>
                                <div><a><span class="icon-person"></span> Admin</a></div>
                                <div><a><span class="icon-chat"></span> 19</a></div>
                            </div>
                        </div>
                    </div>
                    <div class="block-21 d-flex mb-4">
                        <figure class="mr-3">
                            <img src="images/img_3.jpg" alt class="img-fluid">
                        </figure>
                        <div class="text">
                            <h3 class="heading"><a >Our Luxury Hotel &amp; Restaurants</a></h3>
                            <div class="meta">
                                <div><a ><span class="icon-calendar"></span> May 29, 2018</a></div>
                                <div><a ><span class="icon-person"></span> Admin</a></div>
                                <div><a ><span class="icon-chat"></span> 19</a></div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-md-6 col-lg-4">
                    <div class="block-23">
                        <h3 class="heading-section">Contact Info</h3>
                        <ul>
                            <li>
                                <span class="icon icon-map-marker"></span><span class="text">
                                    203 Fake St. Mountain View, San
                                    Francisco, California, USA
                                </span>
                            </li>
                            <li><a ><span class="icon icon-phone"></span><span class="text">+2 392 3929 210</span></a></li>
                            <li>
                                <a >
                                    <span class="icon icon-envelope"></span><span class="text">
                                        <span class="__cf_email__"
                                              data-cfemail="e38a8d858ca39a8c9691878c8e828a8dcd808c8e">[email&#160;protected]</span>
                                    </span>
                                </a>
                            </li>
                            <li>
                                <span class="icon icon-clock-o"></span><span class="text">Monday &mdash; Friday 8:00am - 5:00pm</span>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
            <div class="row pt-5">
                <div class="col-md-12 text-left">
                    <p>

                        Copyright &copy;
                        <script data-cfasync="false"
                                src="../../cdn-cgi/scripts/5c5dd728/cloudflare-static/email-decode.min.js"></script>
                        <script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with
                        <i class="icon-heart" aria-hidden="true"></i> by <a target="_blank"
                                                                            class="text-primary">Colorlib</a>

                    </p>
                </div>
            </div>
        </div>
    </footer>

        <script src="~/js/jquery.min.js"></script>
        <script src="~/js/jquery-migrate-3.0.1.min.js"></script>
        <script src="~/js/popper.min.js"></script>
        <script src="~/js/bootstrap.min.js"></script>
        <script src="~/js/jquery.easing.1.3.js"></script>
        <script src="~/js/jquery.waypoints.min.js"></script>
        <script src="~/js/jquery.stellar.min.js"></script>
        <script src="~/js/owl.carousel.min.js"></script>
        <script src="~/js/jquery.magnific-popup.min.js"></script>
        <script src="~/js/bootstrap-datepicker.js"></script>
        <script src="~/js/aos.js"></script>
        <script src="~/js/jquery.animateNumber.min.js"></script>
        <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBVWaKrjvy3MaE7SQ74_uJiULgl1JY0H2s&amp;sensor=false"></script>
        <script src="~/js/google-map.js"></script>
        <script src="~/js/main.js"></script>

        <script async src="https://www.googletagmanager.com/gtag/js?id=UA-23581568-13"></script>
        <script>
            window.dataLayer = window.dataLayer || [];
            function gtag() { dataLayer.push(arguments); }
            gtag('js', new Date());

            gtag('config', 'UA-23581568-13');
        </script>
        <script defer src="https://static.cloudflareinsights.com/beacon.min.js/v8b253dfea2ab4077af8c6f58422dfbfd1689876627854"
                integrity="sha512-bjgnUKX4azu3dLTVtie9u6TKqgx29RBwfj3QXYt5EKfWM/9hPSAI/4qcV5NACjwAo8UtTeWefx6Zq5PHcMm7Tg=="
                data-cf-beacon='{"rayId":"812fa7b6ce10c7b2","version":"2023.8.0","b":1,"token":"cd0b4b3a733644fc843ef0b185f98241","si":100}'
                crossorigin="anonymous"></script>
</body>
</html>

Views/Shared/_LayoutStaff.cshtml
<!DOCTYPE html>
<html lang="en">

<!-- Mirrored from preview.colorlib.com/theme/brighthotel/ by HTTrack Website Copier/3.x [XR&CO'2014], Sun, 08 Oct 2023 16:10:38 GMT -->
<head>
    <title>Bright Hotel - Free Bootstrap 4 Template by Colorlib</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link href="https://fonts.googleapis.com/css?family=Rubik:300,400,500" rel="stylesheet">
    <link rel="stylesheet" href="~/css/open-iconic-bootstrap.min.css">
    <link rel="stylesheet" href="~/css/animate.css">
    <link rel="stylesheet" href="~/css/owl.carousel.min.css">
    <link rel="stylesheet" href="~/css/owl.theme.default.min.css">
    <link rel="stylesheet" href="~/css/magnific-popup.css">
    <link rel="stylesheet" href="~/css/aos.css">
    <link rel="stylesheet" href="~/css/ionicons.min.css">
    <link rel="stylesheet" href="~/css/bootstrap-datepicker.css">
    <link rel="stylesheet" href="~/css/jquery.timepicker.css">
    <link rel="stylesheet" href="~/css/flaticon.css">
    <link rel="stylesheet" href="~/css/icomoon.css">
    <link rel="stylesheet" href="~/css/style.css">
    <script nonce="4516a2da-1752-4584-bdf4-697bcb381c29">(function (w, d) { !function (a, b, c, d) { a[c] = a[c] || {}; a[c].executed = []; a.zaraz = { deferred: [], listeners: [] }; a.zaraz.q = []; a.zaraz._f = function (e) { return async function () { var f = Array.prototype.slice.call(arguments); a.zaraz.q.push({ m: e, a: f }) } }; for (const g of ["track", "set", "debug"]) a.zaraz[g] = a.zaraz._f(g); a.zaraz.init = () => { var h = b.getElementsByTagName(d)[0], i = b.createElement(d), j = b.getElementsByTagName("title")[0]; j && (a[c].t = b.getElementsByTagName("title")[0].text); a[c].x = Math.random(); a[c].w = a.screen.width; a[c].h = a.screen.height; a[c].j = a.innerHeight; a[c].e = a.innerWidth; a[c].l = a.location.href; a[c].r = b.referrer; a[c].k = a.screen.colorDepth; a[c].n = b.characterSet; a[c].o = (new Date).getTimezoneOffset(); if (a.dataLayer) for (const n of Object.entries(Object.entries(dataLayer).reduce(((o, p) => ({ ...o[1], ...p[1] })), {}))) zaraz.set(n[0], n[1], { scope: "page" }); a[c].q = []; for (; a.zaraz.q.length;) { const q = a.zaraz.q.shift(); a[c].q.push(q) } i.defer = !0; for (const r of [localStorage, sessionStorage]) Object.keys(r || {}).filter((t => t.startsWith("_zaraz_"))).forEach((s => { try { a[c]["z_" + s.slice(7)] = JSON.parse(r.getItem(s)) } catch { a[c]["z_" + s.slice(7)] = r.getItem(s) } })); i.referrerPolicy = "origin"; i.src = "../../cdn-cgi/zaraz/sd0d9.js?z=" + btoa(encodeURIComponent(JSON.stringify(a[c]))); h.parentNode.insertBefore(i, h) };["complete", "interactive"].includes(b.readyState) ? zaraz.init() : a.addEventListener("DOMContentLoaded", zaraz.init) }(w, d, "zarazData", "script"); })(window, document);</script>
</head>

<body>


    <header>
        <nav class="navbar navbar-expand-lg navbar-dark ftco_navbar bg-dark ftco-navbar-light" style="background: transparent !important;position: absolute; " id="ftco-navbar">
            <div class="container">
                <a class="navbar-brand">BrightHotel</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#ftco-nav" aria-controls="ftco-nav" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="oi oi-menu"></span> Menu
                </button>
                <div class="collapse navbar-collapse" id="ftco-nav">
                    <ul class="navbar-nav ml-auto">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Staff" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Staff" asp-action="rooms">Rooms</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>



    @RenderBody();
    @await RenderSectionAsync("Scripts", required: false)


    <script src="~/js/jquery.min.js"></script>
    <script src="~/js/jquery-migrate-3.0.1.min.js"></script>
    <script src="~/js/popper.min.js"></script>
    <script src="~/js/bootstrap.min.js"></script>
    <script src="~/js/jquery.easing.1.3.js"></script>
    <script src="~/js/jquery.waypoints.min.js"></script>
    <script src="~/js/jquery.stellar.min.js"></script>
    <script src="~/js/owl.carousel.min.js"></script>
    <script src="~/js/jquery.magnific-popup.min.js"></script>
    <script src="~/js/bootstrap-datepicker.js"></script>
    <script src="~/js/aos.js"></script>
    <script src="~/js/jquery.animateNumber.min.js"></script>
    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBVWaKrjvy3MaE7SQ74_uJiULgl1JY0H2s&amp;sensor=false"></script>
    <script src="~/js/google-map.js"></script>
    <script src="~/js/main.js"></script>

    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-23581568-13"></script>
    <script>
        window.dataLayer = window.dataLayer || [];
        function gtag() { dataLayer.push(arguments); }
        gtag('js', new Date());

        gtag('config', 'UA-23581568-13');
    </script>
    <script defer src="https://static.cloudflareinsights.com/beacon.min.js/v8b253dfea2ab4077af8c6f58422dfbfd1689876627854"
            integrity="sha512-bjgnUKX4azu3dLTVtie9u6TKqgx29RBwfj3QXYt5EKfWM/9hPSAI/4qcV5NACjwAo8UtTeWefx6Zq5PHcMm7Tg=="
            data-cf-beacon='{"rayId":"812fa7b6ce10c7b2","version":"2023.8.0","b":1,"token":"cd0b4b3a733644fc843ef0b185f98241","si":100}'
            crossorigin="anonymous"></script>
</body>
</html>

Views/Shared/_Login.cshtml
<!DOCTYPE html>
<html lang="en" class="h-100">


<!-- Mirrored from kamr.dexignlab.com/xhtml/page-lock-screen.html by HTTrack Website Copier/3.x [XR&CO'2014], Sun, 12 Nov 2023 16:24:19 GMT -->
<!-- Mirrored from kamr.dexignlab.com/xhtml/page-login.html by HTTrack Website Copier/3.x [XR&CO'2014], Sun, 12 Nov 2023 16:24:17 GMT -->
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="keywords" content="" />
	<meta name="author" content="" />
	<meta name="robots" content="" />
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta name="description" content="Kamr Hotel Admin Dashboard" />
	<meta property="og:title" content="Kamr Hotel Admin Dashboard" />
	<meta property="og:description" content="Kamr Hotel Admin Dashboard" />
	<meta property="og:image" content="social-image.png" />
	<meta name="format-detection" content="telephone=no">

	<!-- PAGE TITLE HERE -->
	<title>Kamr Hotel Admin Dashboard</title>

	<!-- FAVICONS ICON -->
	<link rel="shortcut icon" type="image/png" href="images/favicon.png" />
	<link href="~/vendor/bootstrap-select/dist/css/bootstrap-select.min.css" rel="stylesheet">
	<link href="~/vendor/jquery-nice-select/css/nice-select.css" rel="stylesheet">
	<link href="~/css/styleAdmin.css" rel="stylesheet">

</head>

<body class="vh-100">

	@RenderBody();
	@await RenderSectionAsync("Scripts", required: false)

</body>
	
<!-- #/ container -->
<!-- Common JS -->
<script src="~/vendor/global/global.min.js"></script>
<!-- Custom script -->
<script src="~/vendor/deznav/deznav.min.js"></script>
<script src="~/js/custom.min.js"></script>
<script src="~/js/deznav-init.js"></script>
<script src="~/vendor/bootstrap-select/dist/js/bootstrap-select.min.js"></script>
<script src="~/vendor/jquery-nice-select/js/jquery.nice-select.min.js"></script>
<script src="~/js/demo.js"></script>
<script src="~/js/styleSwitcher.js"></script>
<!-- Mirrored from kamr.dexignlab.com/xhtml/page-lock-screen.html by HTTrack Website Copier/3.x [XR&CO'2014], Sun, 12 Nov 2023 16:24:19 GMT -->
</html>